[package]
name = "RustQtCalculator"
version = "0.1.0"
edition = "2024"


[dependencies]
qtbridge = "0.2.0"


[build-dependencies]
vcpkg = "0.2"
toml = "0.8"



########################################################################################################################
# vcpkg for c/c++ dependencies
########################################################################################################################

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "master"


# x64 Windows
[package.metadata.vcpkg.target.x86_64-pc-windows-msvc]
dependencies = ["qtbase", "qtdeclarative", "qttools", "qtsvg"]
triplet="x64-windows"


# arm64 Windows
[package.metadata.vcpkg.target.arm64-pc-windows-msvc]
dependencies = ["qtbase", "qtdeclarative", "qttools", "qtsvg"]
triplet="arm64-windows"


# arm64 macOS
[package.metadata.vcpkg.target.arm64-apple-darwin]
dependencies = ["qtbase", "qtdeclarative", "qttools", "qtsvg"]
triplet = "arm64-osx"


# x64 Linux
[package.metadata.vcpkg.target.x86_64-unknown-linux-gnu]
dependencies = ["qtbase[gtk3]", "qtdeclarative", "qttools", "qtsvg", "qtwayland"]
triplet = "arm64-linux"

