#!/usr/bin/env sh


## Get vcpkg triplet for the current build host
#  Uses dynmaic linked triplets b/c QT does not support static linking well
vcpkg_host_triplet() {
    ARCH="unknown"
    case "$(uname -m)" in
        x86_64)
            ARCH="x64"
            ;;
        i686|i586|i486|i386)
            ARCH="x86"
            ;;
        arm64|aarch64)
            ARCH="arm64"
            ;;
    esac
    OS="unknown"
    case "$(uname -o)" in
        Msys|"MS/Windows")
            OS="windows"
            ;;
        Darwin)
            OS="osx-dynamic"
            ;;
        "GNU/Linux")
            OS="linux-dynamic"
            ;;
    esac
    echo "$ARCH-$OS"
}


## Parse cargo command line arguments to extract target and map to vcpkg triplet
vcpkg_target_triplet(){
    while [ $# -gt 0 ]; do
    case "$1" in
        --target)
            case "$2" in
                "x86_64-pc-windows-msvc")
                    echo "x64-windows"
                    ;;
                "arm64-pc-windows-msvc")
                    echo "arm64-windows"
                    ;;
                "arm64-apple-darwin")
                    echo "arm64-osx-dynamic"
                    ;;
                "arm64-unknown-linux-gnu")
                    echo "x64-linux-dynamic"
                    ;;
                *)
                    echo "unknown"
                    ;;
            esac
            return 0
            ;;
        *)
            shift
            ;;
    esac
    done
    # If no target specified, assume compiling for host
    vcpkg_host_triplet
}


# Setup everything correctly for vcpkg
export NO_VCPKG
if [ "$NO_VCPKG" != "1" ]; then
    # Ensure vcpkg root is set
    VCPKG_ROOT="${VCPKG_ROOT:=$HOME/vcpkg}"
    if [ "$(uname -o)" = "Msys" ]; then
        VCPKG_ROOT="$(cygpath -u "$VCPKG_ROOT")"
    fi

    # Set vcpkg triplets properly
    export VCPKG_DEFAULT_HOST_TRIPLET="$(vcpkg_host_triplet)"
    export VCPKG_DEFAULT_TRIPLET="$(vcpkg_target_triplet "$@")"
    export VCPKGRS_DYNAMIC=1
    export VCPKGRS_TRIPLET="$VCPKG_DEFAULT_TRIPLET"

    # Prepend QT tools path to PATH before invoking cargo
    # This is the only way to get qtbridge crate to find QT properly
    # since build.rs cannot modify the env var in a way that impacts other crates
    export PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/tools/Qt6/bin/:$PATH"

    # Setup so cargow run will be able to run app finding correct dynamic libs from vcpkg
    case "$(uname -o)" in
        Msys|"MS/Windows")
            export PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/lib/:$PATH"
            ;;
        Darwin)
            export DYLD_LIBRARY_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/lib:$DYLD_LIBRARY_PATH"
            ;;
        "GNU/Linux")
            export LD_LIBRARY_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/lib/:$LD_LIBRARY_PATH"
            ;;
    esac
    export QT_PLUGIN_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/Qt6/plugins"
    export QML_IMPORT_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_HOST_TRIPLET/Qt6/qml"
fi


# Invoke cargo passing through args
cargo "$@"

